version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - docker.env

  redis:
    image: redis/redis-stack
    container_name: redis
    volumes:
      - redis:/data
    networks:
      - redis
    ports:
      - "6379:6380"
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: pgAdmin
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgAdmin:/root/.pgadmin
    env_file:
      - docker.env
  st-agent:
    image: sematext/agent:latest
    privileged: true
    environment:
      - INFRA_TOKEN=04ba0b19-88c0-4917-ab85-9ee386b245c7
      - SERVER_BASE_URL=https://spm-receiver.sematext.com
      - LOGS_RECEIVER_URL=https://logsene-receiver.sematext.com
      - EVENT_RECEIVER_URL=https://event-receiver.sematext.com
      - COMMAND_SERVER_URL=https://command.sematext.com
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - /:/hostfs:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /var/run/:/var/run
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys:/host/sys:ro
      - /dev:/hostfs/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nestjs-api:
    image: nestjs-api
    container_name: nestjs-api
    env_file:
      - docker.env
    environment:
      - MONITORING_TOKEN=82a7c71c-8323-4144-ad30-49a5f6359e20
      - INFRA_TOKEN=04ba0b19-88c0-4917-ab85-9ee386b245c7
    ports:
      - "4040:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - redis
volumes:
  postgres:
  pgAdmin:
  redis:
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
